# Generated by Django 4.2.3 on 2023-09-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_login_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
